version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/animalpocketresources/
permissions:
  - object: /home/ec2-user/animalpocketresources/cmd/main
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: run.sh
     timeout: 300
     runas: ec2-user
