services:
  web:
    build: .
    working_dir: /usr/src/app
    env_file:
     - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${ secrets.DB_USER }
      - POSTGRES_PASSWORD=${ secrets.DB_PASSWORD }
      - POSTGRES_DB=${ secrets.DB_NAME }
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
