services:
  web:
    build: .
    working_dir: /usr/src/app
    env_file:
     - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  swagger-ui:
    image: swaggerapi/swagger-ui

    environment:
      - SWAGGER_JSON=/docs/swagger.json
    ports:
      - "8080:8080"
    volumes:
      - .:/docs  

volumes:
  postgres-db:
